In [101]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle

In [102]:
data1='C:\\Users\\Ajieh Daniel\\Desktop\\3mtt project End to End\\archive\\Social_Network_Ads.csv'

In [103]:
Adclick=pd.read_csv(data1)

In [104]:
Adclick.describe


<bound method NDFrame.describe of       User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]>

In [105]:
Adclick.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [106]:
Adclick.head(20)

User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510    Male   19            19000          0
1   15810944    Male   35            20000          0
2   15668575  Female   26            43000          0
3   15603246  Female   27            57000          0
4   15804002    Male   19            76000          0
5   15728773    Male   27            58000          0
6   15598044  Female   27            84000          0
7   15694829  Female   32           150000          1
8   15600575    Male   25            33000          0
9   15727311  Female   35            65000          0
10  15570769  Female   26            80000          0
11  15606274  Female   26            52000          0
12  15746139    Male   20            86000          0
13  15704987    Male   32            18000          0
14  15628972    Male   18            82000          0
15  15697686    Male   29            80000          0
16  15733883    Male   47            25000          1
17  15617482    Male   45            26000          1
18  15704583    Male   46            28000          1
19  15621083  Female   48            29000          1

In [107]:
print(Adclick.isnull().sum())

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64


In [127]:

# Define categorical features
categorical_features = ["Gender"]  # Update with actual categorical features

# Create and fit LabelEncoder using STRING values
label_encoders = {"Gender": LabelEncoder()}
Adclick["Gender"] = label_encoders["Gender"].fit_transform(Adclick["Gender"])

# Save LabelEncoders
joblib.dump(label_encoders, "label_encoders.joblib")
print("✅ LabelEncoders saved successfully!")


✅ LabelEncoders saved successfully!


In [108]:
# Sample categorical features
categorical_features = ["Gender"]  # Update with actual features

# Create a dictionary to store LabelEncoders
label_encoders1 = {}

for feature in categorical_features:
    le = LabelEncoder()
    Adclick['Gender'] = le.fit_transform(Adclick['Gender'])
    label_encoders1['Gender'] = LabelEncoder()  # Initialize encoder
# Encoding categorical variable (e.g., Gender)







In [109]:
# Selecting Features and Target
X = Adclick[['Age', 'EstimatedSalary', 'Gender']]
y = Adclick['Purchased']

In [110]:
X

Age  EstimatedSalary  Gender
0     19            19000       1
1     35            20000       1
2     26            43000       0
3     27            57000       0
4     19            76000       1
..   ...              ...     ...
395   46            41000       0
396   51            23000       1
397   50            20000       0
398   36            33000       1
399   49            36000       0

[400 rows x 3 columns]

In [111]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [112]:
# Splitting into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [113]:
# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [114]:
# Step 3: Model Training
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [115]:
# Calculate training score
y_train_pred = model.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_pred)
print("Training Accuracy:", train_accuracy)

# Step 4: Model Evaluation
y_pred = model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", test_accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Training Accuracy: 1.0
Test Accuracy: 0.88125
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.90      0.90       100
           1       0.84      0.85      0.84        60

    accuracy                           0.88       160
   macro avg       0.87      0.88      0.87       160
weighted avg       0.88      0.88      0.88       160

Confusion Matrix:
 [[90 10]
 [ 9 51]]


In [116]:
from sklearn.linear_model import LogisticRegression
# -------------------- Logistic Regression --------------------
print("\n--- Logistic Regression ---")
lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train, y_train)

# Training score
y_train_pred_lr = lr_model.predict(X_train)
train_accuracy_lr = accuracy_score(y_train, y_train_pred_lr)
print("Training Accuracy:", train_accuracy_lr)

# Evaluation
y_pred_lr = lr_model.predict(X_test)
test_accuracy_lr = accuracy_score(y_test, y_pred_lr)
print("Test Accuracy:", test_accuracy_lr)
print("Classification Report:\n", classification_report(y_test, y_pred_lr))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))


--- Logistic Regression ---
Training Accuracy: 0.8125
Test Accuracy: 0.85
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.96      0.89       100
           1       0.91      0.67      0.77        60

    accuracy                           0.85       160
   macro avg       0.87      0.81      0.83       160
weighted avg       0.86      0.85      0.84       160

Confusion Matrix:
 [[96  4]
 [20 40]]


In [117]:
from sklearn.svm import SVC
# -------------------- Support Vector Machine (SVM) --------------------
print("\n--- Support Vector Machine (SVM) ---")
svm_model = SVC(random_state=42) # You might want to experiment with kernel='linear', 'rbf', 'poly', etc.
svm_model.fit(X_train, y_train)

# Training score
y_train_pred_svm = svm_model.predict(X_train)
train_accuracy_svm = accuracy_score(y_train, y_train_pred_svm)
print("Training Accuracy:", train_accuracy_svm)

# Evaluation
y_pred_svm = svm_model.predict(X_test)
test_accuracy_svm = accuracy_score(y_test, y_pred_svm)
print("Test Accuracy:", test_accuracy_svm)
print("Classification Report:\n", classification_report(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))



--- Support Vector Machine (SVM) ---
Training Accuracy: 0.9041666666666667
Test Accuracy: 0.925
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.92      0.94       100
           1       0.88      0.93      0.90        60

    accuracy                           0.93       160
   macro avg       0.92      0.93      0.92       160
weighted avg       0.93      0.93      0.93       160

Confusion Matrix:
 [[92  8]
 [ 4 56]]


In [118]:
from sklearn.neighbors import KNeighborsClassifier
# -------------------- K-Nearest Neighbors (KNN) --------------------
print("\n--- K-Nearest Neighbors (KNN) ---")
knn_model = KNeighborsClassifier(n_neighbors=5) # You'll likely want to tune 'n_neighbors'
knn_model.fit(X_train, y_train)

# Training score
y_train_pred_knn = knn_model.predict(X_train)
train_accuracy_knn = accuracy_score(y_train, y_train_pred_knn)
print("Training Accuracy:", train_accuracy_knn)

# Evaluation
y_pred_knn = knn_model.predict(X_test)
test_accuracy_knn = accuracy_score(y_test, y_pred_knn)
print("Test Accuracy:", test_accuracy_knn)
print("Classification Report:\n", classification_report(y_test, y_pred_knn))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))



--- K-Nearest Neighbors (KNN) ---
Training Accuracy: 0.9041666666666667
Test Accuracy: 0.9125
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.92      0.93       100
           1       0.87      0.90      0.89        60

    accuracy                           0.91       160
   macro avg       0.90      0.91      0.91       160
weighted avg       0.91      0.91      0.91       160

Confusion Matrix:
 [[92  8]
 [ 6 54]]


In [119]:
from sklearn.tree import DecisionTreeClassifier
# -------------------- Decision Tree --------------------
print("\n--- Decision Tree ---")
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# Training score
y_train_pred_dt = dt_model.predict(X_train)
train_accuracy_dt = accuracy_score(y_train, y_train_pred_dt)
print("Training Accuracy:", train_accuracy_dt)

# Evaluation
y_pred_dt = dt_model.predict(X_test)
test_accuracy_dt = accuracy_score(y_test, y_pred_dt)
print("Test Accuracy:", test_accuracy_dt)
print("Classification Report:\n", classification_report(y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))


--- Decision Tree ---
Training Accuracy: 1.0
Test Accuracy: 0.86875
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.90      0.90       100
           1       0.83      0.82      0.82        60

    accuracy                           0.87       160
   macro avg       0.86      0.86      0.86       160
weighted avg       0.87      0.87      0.87       160

Confusion Matrix:
 [[90 10]
 [11 49]]


In [120]:
from sklearn.ensemble import GradientBoostingClassifier
# -------------------- Gradient Boosting --------------------
print("\n--- Gradient Boosting ---")
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gb_model.fit(X_train, y_train)

# Training score
y_train_pred_gb = gb_model.predict(X_train)
train_accuracy_gb = accuracy_score(y_train, y_train_pred_gb)
print("Training Accuracy:", train_accuracy_gb)

# Evaluation
y_pred_gb = gb_model.predict(X_test)
test_accuracy_gb = accuracy_score(y_test, y_pred_gb)
print("Test Accuracy:", test_accuracy_gb)
print("Classification Report:\n", classification_report(y_test, y_pred_gb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gb))


--- Gradient Boosting ---
Training Accuracy: 0.975
Test Accuracy: 0.90625
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.93      0.93       100
           1       0.88      0.87      0.87        60

    accuracy                           0.91       160
   macro avg       0.90      0.90      0.90       160
weighted avg       0.91      0.91      0.91       160

Confusion Matrix:
 [[93  7]
 [ 8 52]]


In [121]:
click_pred = Adclick[['Gender','Age','EstimatedSalary',]]
click_pred.shape

(400, 3)

In [122]:
pred_click = knn_model.predict(click_pred)
pred_click.shape

c:\Users\Ajieh Daniel\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


(400,)

In [123]:
click_pred['Pred_click']=pred_click # creation of new column and assign predicted value from ml algorithm
click_pred['Purchased']=Adclick['Purchased'] # creation of new column and assign original E_DTP value from well
click_pred

C:\Users\Ajieh Daniel\AppData\Local\Temp\ipykernel_4700\604366803.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  click_pred['Pred_click']=pred_click # creation of new column and assign predicted value from ml algorithm


Gender  Age  EstimatedSalary  Pred_click  Purchased
0         1   19            19000           1          0
1         1   35            20000           1          0
2         0   26            43000           1          0
3         0   27            57000           1          0
4         1   19            76000           1          0
..      ...  ...              ...         ...        ...
395       0   46            41000           1          1
396       1   51            23000           1          1
397       0   50            20000           1          1
398       1   36            33000           1          0
399       0   49            36000           1          1

[400 rows x 5 columns]

In [124]:
import joblib
# Save the trained model
joblib.dump(knn_model, 'knn_purchase_model.joblib')

# Save the scaler
joblib.dump(scaler, 'feature_scaler.joblib')

# Save the LabelEncoders
joblib.dump(le, 'label_encoders1.joblib')

print("Model, scaler, and label encoders saved successfully!")

Model, scaler, and label encoders saved successfully!


In [125]:
le = joblib.load("label_encoders.joblib")

# Check its type
print(type(le))

# If it's a dictionary, print the keys
if isinstance(le, dict):
    print("Keys:", le.keys())
else:
    print("The loaded object is not a dictionary.")

FileNotFoundError: [Errno 2] No such file or directory: 'label_encoders.joblib'

Encoders

In [ ]:
import joblib
from sklearn.preprocessing import LabelEncoder



# Save the dictionary properly
joblib.dump(label_encoders1, "label_encoders1.joblib")

print("✅ Label Encoders saved correctly as a dictionary.")


✅ Label Encoders saved correctly as a dictionary.


SyntaxError: invalid syntax (1953205855.py, line 66)

KNN Had the best score so, we are going to use it to make predictions.


# Step 5: Save Model for Future Use


c:\Users\Ajieh Daniel\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


ValueError: X has 5 features, but KNeighborsClassifier is expecting 3 features as input.

     Actual Purchase  Predicted Purchase
209                0                   1
280                1                   1
33                 0                   0
210                1                   1
93                 0                   0
..               ...                 ...
246                0                   0
227                1                   1
369                1                   1
176                0                   0
289                1                   0

[80 rows x 2 columns]

Test Accuracy of KNN Model: 0.9250

--- Misclassified Instances ---
     Actual Purchase  Predicted Purchase
209                0                   1
42                 0                   1
172                0                   1
352                1                   0
73                 0                   1
289                1                   0


      User ID  Gender  Age  EstimatedSalary  Purchased  \
0    15624510       1   19            19000          0   
1    15810944       1   35            20000          0   
2    15668575       0   26            43000          0   
3    15603246       0   27            57000          0   
4    15804002       1   19            76000          0   
..        ...     ...  ...              ...        ...   
395  15691863       0   46            41000          1   
396  15706071       1   51            23000          1   
397  15654296       0   50            20000          1   
398  15755018       1   36            33000          0   
399  15594041       0   49            36000          1   

     Predicted Purchase (KNN)  
0                           1  
1                           1  
2                           1  
3                           1  
4                           1  
..                        ...  
395                         1  
396                         1  
397            

c:\Users\Ajieh Daniel\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


DataFrame successfully downloaded to 'predicted_data.csv'


User ID      Gender         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000  400.000000       400.000000  400.000000
mean   1.569154e+07    0.490000   37.655000     69742.500000    0.357500
std    7.165832e+04    0.500526   10.482877     34096.960282    0.479864
min    1.556669e+07    0.000000   18.000000     15000.000000    0.000000
25%    1.562676e+07    0.000000   29.750000     43000.000000    0.000000
50%    1.569434e+07    0.000000   37.000000     70000.000000    0.000000
75%    1.575036e+07    1.000000   46.000000     88000.000000    1.000000
max    1.581524e+07    1.000000   60.000000    150000.000000    1.000000

<bound method NDFrame.describe of       User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]>